name: boulder-buddy

services:
  database:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # seeding
      # - ./backend/database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # named volume
      - bb-pg-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    hostname: api
    build:
      context: ./backend
      target: ${APP_ENV}
      args:
        APP_HOME: ${APP_HOME}
    ports:
      - 3500:8000
    volumes:
      - ./backend:${APP_HOME}
    links:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: ${APP_ENV}
      args:
        APP_HOME: ${APP_HOME}
    volumes:
      - ./frontend:${APP_HOME}
    ports:
      - 5173:5173

volumes:
  bb-pg-data:
    external: true
