basePath: /api/v1
definitions:
  handlers.Error:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/utils.errorCode'
        description: Machine-readable error code.
      fields:
        description: Some context of error
        items:
          type: string
        type: array
      message:
        description: Human-readable message.
        type: string
      op:
        description: Logical operation.
        type: string
      stack:
        description: Wrapped error
    type: object
  handlers.Mesocycle:
    properties:
      description:
        type: string
      endDate:
        type: integer
      goal:
        type: string
      isActive:
        type: boolean
      numMicros:
        type: integer
      startDate:
        type: integer
    type: object
  router.Response:
    properties:
      message:
        type: string
    type: object
  utils.errorCode:
    enum:
    - conflict
    - internal
    - invalid
    - not_found
    - not_modified
    - already_exists
    - permission_denied
    - unauthenticated
    - cannot_decode
    - cannot_encode
    - cannot_parse
    - undefined_behavior
    - unsupported
    - test_error_code
    type: string
    x-enum-varnames:
    - ECONFLICT
    - EINTERNAL
    - EINVALID
    - ENOTFOUND
    - ENOTMODIFIED
    - EALREADYEXISTS
    - EPERMISSIONDENIED
    - EUNAUTHENTICATED
    - ECANNOTDECODE
    - ECANNOTENCODE
    - ECANNOTPARSE
    - EBEHAVIOUR
    - EUNSUPPORTED
    - ETEST
host: localhost:3500
info:
  contact: {}
  title: Boulder Buddy API
  version: "1.0"
paths:
  /:
    get:
      description: retrieve server status
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.Response'
      summary: Healthcheck
  /mesos:
    get:
      description: get all mesocyles for current user
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.Mesocycle'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Retrieve mesocyles
      tags:
      - Mesos
    post:
      description: create a new mesocycle
      parameters:
      - description: new mesocycle info
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handlers.Mesocycle'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Mesocycle'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Create a mesocyle
      tags:
      - Mesos
schemes:
- http
swagger: "2.0"
